### ISSUE TITLE
compiled version (v1.4.4) is only using half CPU power on MacOS 

### ISSUE THREAD

**Issue by yangcht** [editeodoro/Bbarolo#13]
Hi EdT,

I switched from the pre-compiled binary (OSX) to the version I compiled myself on my MacOS 10.14.6 (default configuration). I found the latter is very slow and only using half of my CPU, while the pre-compiled version (https://github.com/editeodoro/Bbarolo/releases/tag/1.4) is using the full CPU. 

Do you have any idea why this is happening? 

Many thanks!!

**Comment by yangcht** [comment]
Sorry, I think it might be related to OpenMP support. My compiled version does not support OpenMP.

**Comment by editeodoro** [comment]
Please remember that default compiler in Mac OSX (clang, aliased to gcc) does not support OpenMP.

**Comment by yangcht** [comment]
Update: using 

> `export CXX=clang++-mp-8.0`
