### ISSUE TITLE
Feature: Fit Velocity boundaries

### ISSUE THREAD

**Issue by Mixpap** [editeodoro/Bbarolo#14]
Hello and thank you for this amazing code and effort.
So this is a feature request, or a question if I didn't read the documentation very well.
In case the user provides a Vrot (a value or a model from a file) the code should support some boundaries so it fits for every ring a value within (Vrot-DELTAV,Vrot+DELTAV).
Thanks again!

**Comment by editeodoro** [comment]
Hi Michalis, 
thanks for using BBarolo! I have now implemented this feature in the latest commit, you can now use the parameter DELTAVROT to set the boundaries for the fit of VROT. I havent fully tested it, but it should be ok. Please, let me know if you encounter any misbehaviour of BBarolo.

Cheers, 
Enrico
