### ISSUE TITLE
PA is the receding side?

### ISSUE THREAD

**Issue by teuben** [editeodoro/Bbarolo#21]
I think we may need a clarification in the documentation. The PA is not defined in terms of receding or approaching side, where the convention is receding. The figure with PA=124 does seem to suggest this is indeed receding, but I didn't see it mention.  I'm surprised i'm only noticing this ambiguity now.

**Comment by editeodoro** [comment]
Hi Peter, 
yes, you're right, the PA is defined from the receding side. I am also surprised that I did not specify that in the documentation, thanks for noticing this! I have now updated the docs. 

Enrico
