### ISSUE TITLE
I found a bug, and I fixed it. Can I make a PR for you?

### ISSUE THREAD

**Issue by This-Researcher** [editeodoro/Bbarolo#24]
Hi @editeodoro and @kyleaoman! 

This program is fantastic!

I found a tiny problem though. The output stage fails if the path has spaces in it. For example:
`/home/me/this path has spaces/output/galaxy_files`

Here is a screenshot of the error:
`Something went wrong! Check plotting scripts in the output folder`
![image](https://user-images.githubusercontent.com/98858275/153121803-73afed74-239a-41ae-8fbd-73cfd61329c7.png)

I fixed it by adding escaped quotation marks around the paths. Now, it works with no errors:
![image](https://user-images.githubusercontent.com/98858275/153121964-6fe64dda-317e-4c8c-996a-3e5c54c08b7e.png)

I made a new github branch called "_**bugfix/spaces_in_path**_". May I submit it to your repository as a Pull Request?

**Comment by editeodoro** [comment]
Hi @This-Researcher, 
thanks for finding and fixing this! Sure, feel free to submit a PR.

Cheers, 
Enrico
