### ISSUE TITLE
PyBarolo wget link seems to be outdated or wrong

### ISSUE THREAD

**Issue by 0ort9** [editeodoro/Bbarolo#26]
Hello, i have been trying to install PyBarolo using the wget command. The link from the documentation leads to a 404 error. Is there a up to date link somewhere?
Thanks in advance

**Comment by editeodoro** [comment]
Hello, did you use the following command?

`wget https://github.com/editeodoro/Bbarolo/archive/1.6.tar.gz `

**Comment by 0ort9** [comment]
Thank you it worked. I might have had a typo
