### ISSUE TITLE
I can install BBarolo but not pyBBarolo

### ISSUE THREAD

**Issue by arnbobo** [editeodoro/Bbarolo#27]
Hi there,

I'm trying to replicate an analysis done by one of my collaborators using pyBBarolo in a python script. I've been able to install the command-line BBarolo tool via Homebrew without issue, but I am having trouble installing pyBBarolo. In particular, I'm getting the following message:

      ------ Installing pyBBarolo v1.2.3 ------
      Checking numpy... OK.
      Checking astropy... OK.
      Running BBarolo configure... configure: WARNING: No MPI compiler found, won't use MPI.
      configure: error:
          -------------------------------------------------------------
          Could not find the CFITSIO library.
      
          ERROR: BBarolo configuration failure. If you have the libra-
                 ry in non ordinary path, try to run ./configure with
                 --with-cfitsio=<dir> option
          -------------------------------------------------------------

I'm not sure how to resolve this issue. I do have the dependencies installed (which I did with Conda) - after all, Homebrew was able to find them. I've tried manually adding CFITSIO to $PATH, but this doesn't seem to have changed anything. Do you have any suggestions?

**Comment by arnbobo** [comment]
I figured it out! Adding the library's to $PATH didn't work, but the --with-[LIBRARY] commands did.

**Comment by editeodoro** [comment]
Great, good to hear you solved the issue! Let me know if have any addition problem.
