### ISSUE TITLE
Empty models after fit is successful and problems with python plots 

### ISSUE THREAD

**Issue by jigonzal** [editeodoro/Bbarolo#3]
Hello Enrico, 

I just started using Bbarolo with some ALMA data. After figuring out that the codes expects velocities in the spectral axis instead of frequencies I managed to obtain some successful fits. 
I have the problem that all the mod_local files are empty, full of Nans or zeros. What could be the problem?

About the plots:
I can run the gnuplot script and obtain the plots but the python script fails. 
The spectral axis indexes generated by the code are wrong and fail to select a correct subcube from the original ALMA cube. I fixed this manually in the script.

The second problem is that the python scripts fails at:
norm0 = ImageNormalize(np.nanmin(mom0), np.nanmax(mom0), stretch=LinearStretch()) 
returning:
AttributeError: 'numpy.float32' object has no attribute 'get_limits'

I am using the binaries for mac, 

any advice?

Jorge

**Comment by editeodoro** [comment]
Hi Jorge, 
sorry for the late reply. 
I've added a better support for ALMA datacube in the last weeks. Could you try again to fit your data with the latest repository version?
Also the error in the plots should be now fixed. 

Enrico

**Comment by jigonzal** [comment]
Hello Enrico, 

thanks for the reply. I will try with the new version and let you know how it goes. 

Cheers, 

Jorge
