### ISSUE TITLE
issues for installing BBarolo in Linux

### ISSUE THREAD

**Issue by Couleyr** [editeodoro/Bbarolo#34]
I am trying to install the BBarolo in my computer. 
Its requirements are available in my machine.
However, I got the following error when I ran the command "./congifure" .

----------------------------
Could not find the FFTW3 library

ERROR: BBarolo configuration failure. If you have the library in non ordinary path, try to run ./configure with --whih-fftw3=<dir> option.
-----------------------------

When I manually added the path according to the prompts of the script, I got the same error alert.

**Comment by Couleyr** [comment]
OK , I have solved the above problem!

However, after I successfully ran the command: "./configure" and "make", I entered the "BBarolo" under the corresponding folder of the terminal, but reminded me that the "command not found".

The successfully installed "BBarolo" file also appeared in my Bbarolo-1.7 folder.

I look forward to your reply!

**Comment by editeodoro** [comment]
Hello, if you want to run the BBarolo executable from the directory where you compiled it, you need to type "./BBarolo" rather than just "BBarolo" (this is true for any executable in UNIX, not just BBarolo!). 

If you want to make it available from everywhere in your system, you can either: 
1) copy the executable in a directory which is already in your $PATH ("make install" will copy it by default in /usr/local/bin); 
2) Add the BBarolo-1.7 directory to your $PATH; 
3) Make an alias of BBarolo to where the executable is and add it to your .bashrc (or equivalent for other shells).

Let me know if you have any problems with the above. 
Enrico

**Comment by Couleyr** [comment]
First of all, thank you very much for your reply.
I got the error message : '' ./BBarolo : error while loading shared libraries: libwcs.so.8: cannot open shared object file: No such file or directory", when I ran the commands "./BBarolo" or "BBarolo" in my terminal

**Comment by editeodoro** [comment]
See here, FAQ #1: https://bbarolo.readthedocs.io/en/latest/troubleshooting.html

**Comment by Couleyr** [comment]
OK, thany again!
I have seen this method.
I add the path of libwcs.so.8 library according to this method, and I found that this file is installed in "/use/local/bin/" in my computer!.
But I got the same mistake according to this way.

**Comment by Couleyr** [comment]
Ok, thank you again!
I have seen this method in this web!
I added the path of the "libwcs.so.8" according to this way, and I found this file is installed in '/usr/local/lib'. I donot know if this is normal!
But I got the same mistake according to this way!

**Comment by editeodoro** [comment]
Ok, can you send me the output of the command: "ldd BBarolo"?
Thanks

**Comment by Couleyr** [comment]
OK
![Uploading Ldd_BBarolo.png…]

**Comment by Couleyr** [comment]
OK, It show there is no libwcs.so.8

**Comment by Couleyr** [comment]
OK, it show there is no libwcs.so.8

**Comment by Couleyr** [comment]
OK, it shows there is no libwcs.so.8

![Uploading Ldd_BBarolo.png…]()

**Comment by editeodoro** [comment]
I can't see your attachment. Can you just send it by email if it does not work here? Also, can you send the output of "configure" and "make" steps?
Thanks

**Comment by Couleyr** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Sorry, maybe there is something wrong with my network!The screenshot is my output!
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Peibin Chen
                            
                    
                        
                            
                                    Peibin ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/27/2023 14:52
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Peibin ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [editeodoro/Bbarolo] issues for installing BBarolo in Linux (Issue #34)
        
      
    
  
  
I can't see your attachment. Can you just send it by email if it does not work here? Also, can you send the output of "configure" and "make" steps?
Thanks

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by Couleyr** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Sorry, maybe there is something wrong with my network!The screenshot is my output!
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Peibin Chen
                            
                    
                        
                            
                                    Peibin ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/27/2023 14:52
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Peibin ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [editeodoro/Bbarolo] issues for installing BBarolo in Linux (Issue #34)
        
      
    
  
  
I can't see your attachment. Can you just send it by email if it does not work here? Also, can you send the output of "configure" and "make" steps?
Thanks

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by Couleyr** [comment]
OK, the following pictures are the outputs of the two commands.

<img width="684" alt="截屏2023-11-27 15 21 29" src="https://github.com/editeodoro/Bbarolo/assets/103244840/f4804510-4a5f-4902-bb9a-91b8f7f27ed8">
<img width="725" alt="截屏2023-11-27 15 22 13" src="https://github.com/editeodoro/Bbarolo/assets/103244840/03e989b8-561b-49b4-9149-b29f12070bc9">
<img width="713" alt="截屏2023-11-27 15 22 37" src="https://github.com/editeodoro/Bbarolo/assets/103244840/f68ea037-d709-449e-b64e-db8395a6d606">
<img width="723" alt="截屏2023-11-27 15 23 04" src="https://github.com/editeodoro/Bbarolo/assets/103244840/50a1e23d-5cef-459a-b6c0-bed2d3369281">

**Comment by Couleyr** [comment]
OK, maybe there is something wrong with my network, I am so sorry! The screenshot is the output of the command "ldd BBarolo"
<img width="717" alt="截屏2023-11-27 15 19 10" src="https://github.com/editeodoro/Bbarolo/assets/103244840/1b0bdc23-0be9-42cd-9ae8-47f47adbdbed">

**Comment by editeodoro** [comment]
Do you confirm that if you give the following commands, it still gives the error?

`> export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`
`> export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH`
`> ./BBarolo`

Thanks

**Comment by Couleyr** [comment]
Oh, I found out what went wrong. I wrote the path of this lib as a specific path! I am too stupid.

According to your messages, this program has been successfully run!

This code is very nice!
Thank you very much for all your comments and suggestions!

Best,

**Comment by editeodoro** [comment]
Good to hear that we figure it out! Let me know if you have any further issues.

Enrico
