### ISSUE TITLE
the PA of the outermost ring becomes negative

### ISSUE THREAD

**Issue by BGZJie** [editeodoro/Bbarolo#36]
After I gave BBarolo my initial guesses of PA and inclination, BBarolo gave me a result that the PA of the outmost ring is approximately -280(which I gave 80). Then BBarolo tried to fit -280 into the whole bezier function and made the output pdf look strange. I wonder how to solve the problem.
[maps_local.pdf](https://github.com/editeodoro/Bbarolo/files/13521453/NGC628_maps_local.pdf)
[parameters.pdf](https://github.com/editeodoro/Bbarolo/files/13521456/NGC628_parameters-1.pdf)

**Comment by editeodoro** [comment]
Hello, this is very strange indeed! Would you mind attaching your datacube and parameters, so I can try to figure out what is going wrong?

Thanks, 
Enrico

**Comment by editeodoro** [comment]
I've got the data and deleted your previous message (otherwise, anyone would have been able to download your data!). I'll let you know asap.

**Comment by editeodoro** [comment]
Hello, 
I have investigated the problem and found a little bug that causes the behaviour that you describe. I'll need to fix it, but it may take a few days. In the meanwhile, as a workaround, you can just avoid this problem by explicitly giving the input parameters for the rings in the parameter file. In the example that you sent, the VROT and VDISP were commented out, so the code was trying to estimate them, and that triggered the error with the PA. Just give some values for them and the code should run ok. 

Let me know if this does not solve the issue. 
Cheers, 
Enrico
