### ISSUE TITLE
How to obtain an unnormalized velocity field

### ISSUE THREAD

**Issue by Couleyr** [editeodoro/Bbarolo#38]
Dear Prof.,
Using BBarolo can obtain the normalized velocity field. 
How can I obtain an unnormalized velocity field, i.e. the observed velocity map?
The attachment is an example！

Thank you!
![WechatIMG4124](https://github.com/user-attachments/assets/2b85af6e-bdfb-43ac-a11b-87a713a6462a)

**Comment by editeodoro** [comment]
Hello, 
not sure what you mean for "normalization", do you mean that the velocities are shifted by the systemic velocity. In any case, only the plots from 3DFIT are shifted, while the FITS files of the maps produced by BBarolo are with the "observed" velocities, so you can use them to make your own plots.

Hope this help, 
Enrico

**Comment by Couleyr** [comment]
Dear Prof.,
Thank you very much for your reply!
I'm sorry, I misexpressed myself.
The velocity map BBarolo gave shows that the galaxy's center has a velocity of 0, and we want to determine the velocity of the center (observed velocity). 
Is this consistent with the central velocity obtained by the Gaussian fitting of the integral spectrum?

Cheers,
Peibin

**Comment by editeodoro** [comment]
As I mentioned, If you're looking at the _maps.pdf plot from 3DFIT, that velocity field has been shifted by the systemic velocity, i.e. the galaxy center has always velocity = 0. The maps in FITS format instead give the real recession velocity of the system. Unless you're setting the REDSHIFT parameter, in that case everything is calculated in the redshifted frame of reference. 

Anyway, if you send me your cube and parameter file by email, it would be easier for me to understand.

**Comment by Couleyr** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Dear Prof.,Thank you very much for your reply!We have already set the REDSHIFT parameter in the. par file. The attachment contains our cube and parameter files. Cheers,Peibin
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Peibin Chen
                            
                    
                        
                            
                                    Peibin ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Enrico Di ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/1/2024 15:38
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Peibin ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [editeodoro/Bbarolo] How to obtain an unnormalized velocity field (Issue #38)
        
      
    
  
  
As I mentioned, If you're looking at the _maps.pdf plot from 3DFIT, that velocity field has been shifted by the systemic velocity, i.e. the galaxy center has always velocity = 0. The maps in FITS format instead give the real recession velocity of the system. Unless you're setting the REDSHIFT parameter, in that case everything is calculated in the redshifted frame of reference.
Anyway, if you send me your cube and parameter file by email, it would be easier for me to understand.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by editeodoro** [comment]
Ok, in this case, just set REDSHIFT=0 (or just delete it from your parameter file) and you'll obtain the velocity that you're looking for!

**Comment by Couleyr** [comment]
Ok, thank you very much. The problem has been perfectly solved.

**Comment by editeodoro** [comment]
Great, happy to be helpful! Cheers
