### ISSUE TITLE
COMP: binaries linux missing libpng12

### ISSUE THREAD

**Issue by Punzo** [editeodoro/Bbarolo#6]
Hi Enrico, 

new linux distros (e.g., ubuntu 17.10) do not have anymore libpng12 required from the linux binaries.

**Comment by Punzo** [comment]
P.S.: you may consider to switch your project to cmake (and dynamic libraries). cpack automatizes the packing and solves a lot of these issues.

**Comment by editeodoro** [comment]
Hi Davide, 
yes, I am really struggling in making the binaries with all the needed libraries for general linux distros. I never used cmake, but I'll take a look to it, thanks.
