### ISSUE TITLE
MINOR BUG:  3D Fit parallelization does not seem to work linux

### ISSUE THREAD

**Issue by Punzo** [editeodoro/Bbarolo#8]
I don't see the 3DFit code using the 4 threads as specified in the parameters files (ubuntu 17.10).

Screenshot running meanwhile running 3DFIt (using the fits and par files from example)
![screenshot from 2018-03-28 10-01-34](https://user-images.githubusercontent.com/7985338/38016512-7d762308-326f-11e8-8438-c33ce095b017.png)

configure output
[out.txt](https://github.com/editeodoro/Bbarolo/files/1855030/out.txt)

**Comment by editeodoro** [comment]
Can you also send me a screenshot of the BBarolo's run?

**Comment by Punzo** [comment]
Hi @editeodoro, I rechecked this with last git tag. I does work and the speedup it is nice.

The print of the rings of course it will not be anymore in crescent index order:
[out.txt](https://github.com/editeodoro/Bbarolo/files/1903819/out.txt)

You may think to run the openMP fork in static and print the rings only when a group of N threads has finished the computation (of course this will reduce the performance and probably it is not worth).

I'll close this issue.
