### ISSUE TITLE
MASK=FILE(filename.fits) support in pyBB

### ISSUE THREAD

**Issue by tonywong94** [editeodoro/Bbarolo#9]
Would be great to have input mask FITS file support in pyBBarolo.  Currently exits with an error:

if key=='mask' and op[key][0].upper() not in ['SMOOTH','SEARCH','THRESHOLD','NEGATIVE','SMOOTH&SEARCH','NONE']:
raise ValueError("%s ERROR: %s can only 'SMOOTH','SEARCH','THRESHOLD','NEGATIVE', 'SMOOTH&SEARCH' or 'NONE'."%(self.taskname,key))

I can still run with the regular executable (outside of Python) but let me know if this support may be added soon.

**Comment by editeodoro** [comment]
Added!
